version: 1
formatters:
  default:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
handlers:
  file:
    class: logging.FileHandler
    filename: /var/log/simple_router_access.log
    formatter: default
    level: INFO
  console:
    class: logging.StreamHandler
    formatter: default
    level: INFO
loggers:
  uvicorn:
    handlers: [file, console]
    level: INFO
    propagate: no
  comm_coordinator:
    handlers: [file, console]
    level: INFO
    propagate: no
root:
  handlers: [file, console]
  level: INFO
